import type { Metadata } from "next";
import { Rubik } from "next/font/google";
import "./globals.css";

const geistSans = Rubik({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const myFont = Rubik({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${myFont.className} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
